apiVersion: v2
name: external-secrets
description: Helm chart that deploys External Secrets Operator as an ArgoCD Application into the cluster
type: application
version: 0.1.0

dependencies:
  - name: external-secrets
    version: 0.20.3
    repository: https://charts.external-secrets.io

maintainers:
  - name: Equipo de Plataforma

keywords:
  - external-secrets
  - secrets
  - eso
  - argocd
  - application
