{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.data }}
{{- $externalSecret := . }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "vaultwarden.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ required "externalSecrets.secretStoreRef.name is required" $.Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" | quote }}
  target:
    name: {{ dig "target" "name" $externalSecret.name $externalSecret | quote }}
    creationPolicy: {{ $externalSecret.creationPolicy | default "Owner" | quote }}
  data:
    {{- range $externalSecret.entries }}
    - secretKey: {{ .key | quote }}
      remoteRef:
        key: {{ $externalSecret.remoteRef | quote }}
        property: {{ .property | quote }}
    {{- end }}
{{- end }}
{{- end }}