apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
