valuesObject:
  aws:
    service: SecretsManager
    region: us-east-1
    secretStoreName: argocd-secret-store
    namespace: external-secrets
    serviceAccount:
      name: external-secrets-argocd
      roleArn: arn:aws:iam::111111111111:role/argocd_external_secret_role
