valuesObject:
  dnsEndpoints:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/access: private
    items:
      - name: sonarqube-private-dns
        namespace: sonarqube
        endpoints:
          - dnsName: sonarqube.internal.example.com
            recordTTL: 300
            recordType: CNAME
            targets:
              - gateway.internal.example.com
