{{- if .Values.clusters.enabled }}
{{- range .Values.clusters.items }}
{{- $secretName := .secretName | default (printf "%s-cluster" (regexReplaceAll "[^a-z0-9.-]+" (lower .name) "-")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .annotations .skipReconcile }}
  annotations:
    {{- if .skipReconcile }}
    argocd.argoproj.io/skip-reconcile: "true"
    {{- end }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
stringData:
  name: {{ .name | quote }}
  server: {{ .server | quote }}
  {{- with .namespaces }}
  namespaces: {{ join "," . | quote }}
  {{- end }}
  {{- if hasKey . "clusterResources" }}
  clusterResources: {{ ternary "true" "false" .clusterResources | quote }}
  {{- end }}
  {{- with .project }}
  project: {{ . | quote }}
  {{- end }}
  config: |
{{ mustToPrettyJson .config | indent 4 }}
---
{{- end }}
{{- end }}
