apiVersion: v2
name: vaultwarden
description: Helm chart for deploying Vaultwarden with bundled MySQL
type: application
version: 0.1.0
appVersion: "latest"

maintainers:
  - name: Equipo de Plataforma

keywords:
  - vaultwarden
  - password-manager
  - collaboration
  - mysql
