{{- if and .Values.enabled .Values.externalSecrets.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "externalSecrets.target.name es requerido" .Values.externalSecrets.target.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}

  secretStoreRef:
    name: {{ required "externalSecrets.secretStoreRef.name es requerido" .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}

  target:
    name: {{ required "externalSecrets.target.name es requerido" .Values.externalSecrets.target.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    {{- with .Values.externalSecrets.target.template }}
    template:
    {{ toYaml . | nindent 6 }}
      mergePolicy: Replace
      metadata: {}
    {{- end }}

  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}

{{- end }}
