{{- range $index, $synthetic := .Values.synthetics }}
{{- if gt $index 0 }}
---
{{- end }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ default (printf "%s-alerts" $synthetic.name) $synthetic.ruleName | lower | replace "_" "-" | replace "/" "-" | replace "." "-" }}
  namespace: monitoring
  labels:
    release: {{ $.Values.release | default "internal-prometheus-stack" }}
spec:
  groups:
    - name: blackbox
      rules:
        - alert: {{ default (printf "%s-down" $synthetic.name | lower | replace "_" "-" | replace "/" "-" | replace "." "-") $synthetic.alertName }}
          expr: |
            probe_success{
              {{- range $key, $value := $synthetic.matchLabels }}
              {{ $key }}="{{ $value }}",
              {{- end }}
              environment="{{ $.Values.environment }}"
            } < 1
          for: 3m
          labels:
            account: {{ $.Values.account }}
            service: synthetic
            component: {{ $synthetic.name }}
            severity: critical
            environment: {{ $.Values.environment }}
          annotations:
            summary: "{{ $synthetic.name }} no responde"
            description: "El probe blackbox está fallando para {{ $synthetic.name }}"
{{- end }}
