apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-spc
  namespace: {{ .Release.Namespace }}
spec:
  provider: cce
  parameters:
    objects: |
      {{- range .Values.csmsObjects }}
      - objectName: {{ .objectName | quote }}
        objectType: "csms"
        objectVersion: {{ .objectVersion | default "latest" | quote }}
        {{- with .objectAlias }}
        objectAlias: {{ . | quote }}
        {{- end }}
        {{- with .jmesPath }}
        jmesPath:
          {{- range . }}
          - path: {{ .path }}
            objectAlias: {{ .objectAlias }}
          {{- end }}
        {{- end }}
      {{- end }}
  {{- with .Values.secretObjects }}
  secretObjects:
    {{- range . }}
    - secretName: {{ .secretName }}
      type: {{ .type | default "Opaque" }}
      data:
        {{- range .data }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
        {{- end }}
    {{- end }}
  {{- end }}
