apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cce.io/dew-resource: {{ .Values.serviceAccount.csmsSecrets | toJson | quote }}
